### ISSUE TITLE
uni-app vue3 集成后 微信控制台报错

### ISSUE THREAD

**Issue by Dongary** [growingio/growingio-sdk-miniprogram-autotracker#2]
在uni-app vue3 版本中 npm方式集成后
微信小程序控制台报警告：Avoid app logic that relies on enumerating keys on a component instance. The keys will be empty in production mode to avoid performance overhead，

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/29227408/215650546-37d178a3-de1e-416d-bb4a-5c2624572afa.png">

**Comment by Anoiing** [comment]
你好，该问题已经解决，请升级至最新版本
