### ISSUE TITLE
mPaaS 里网络中断问题。

### ISSUE THREAD

**Issue by cuijiudai** [growingio/growingio-sdk-miniprogram-autotracker#3]
官网有提示：https://growingio.github.io/growingio-sdk-docs/docs/miniprogram/integration/alipay

> 如果您将SDK使用在 mPaaS 中，请注意使用 基础库2.0 进行开发，低版本基础库可能会出现网络请求被意外中断的问题。开发者工具 -> 设置 -> 小程序配置 -> 启用小程序基础库2.0构建

但是为什么呢？我看源码也没改 my.request

**Comment by Anoiing** [comment]
此问题源于支付宝的基础库 1.24.9（2020-10-22）版本的更新。详情请见 https://opendocs.alipay.com/mini/ide/framework-changelog
由于SDK默认5秒请求超时，5秒后会触发cancel逻辑。但由于该版本之前的基础库的问题表现是，cancel请求时会随机cancel一个未结束的请求，而不是当前请求。就可能出现SDK的请求超时的时候可能取消的是客户进行中的业务请求，同时也会导致后续的请求被随机中断。
因此，我们直接要求使用2.x版本的基础库。
